language: ruby
rvm:
  - 2.0.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev libproj0 proj
  - dpkg -S projects.h

before_script:
  - cp config/database.yml-example config/database.yml
  - bundle exec rake db:setup
